### ISSUE TITLE
Implement an AbstractCloudFileStorage interface

### ISSUE THREAD

**Issue by deependujha** [deependujha/go-fsspec#2]
Implement an AbstractCloudFileStorage interface that states the basic functionalities:

- `abstractCloudStorage` will have these methods:
  - `init(cloudProvider string, cloudConfig map[string]string) error`
  - `fileExists(path string) (bool, error)`
  - `makeDirectory(path string) error`
  - `listDirectory(path string) ([]string, error)` / `ls(path string) ([]string, error)`
  - `downloadFile(path string, destination string) error`
  - `uploadFile(path string, source string) error`
  - `downloadDirectory(path string, destination string) error`
  - `uploadDirectory(path string, source string) error`
  - `deleteFile(path string) error`
  - `deleteDirectory(path string) error`

**Comment by emadellaloggia** [comment]
try this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
